spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

info:
  application:
    name: config-server
    description: Servidor de configuraciones centralizado para Sanos y Salvos
    version: 0.0.1-SNAPSHOT
